POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2OTlkMmMxMjMzMThjMmRlMmNjODZiMyIsImlhdCI6MTcyMTM1ODk5NSwiZXhwIjoxNzIxMzYyNTk1fQ.iM5TMG19BogjEhzKxWpTWSmQDJnBXMxiNwsjN7ZJLHc

{
    "content":"rest-api",
    "important":true
}