POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2OWEyNDAyYTBjMmU2YjI3ZjdiZTUwNiIsImlhdCI6MTcyMTM3NzgwNiwiZXhwIjoxNzIxMzgxNDA2fQ.ewfq38nVXO5Wwhqavxdcb8LjTVEh3NNKpOqtPQwiZLc

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf",
    "likes": 5
}