DELETE http://localhost:3001/api/blogs/669a19e8db5a6592fbeb32f4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QxIiwiaWQiOiI2NjlhMTk0NWQxM2Y5Y2ZkNDk1M2FhNmMiLCJpYXQiOjE3MjEzNzUxOTAsImV4cCI6MTcyMTM3ODc5MH0.UoWieB5GcpRRcW1GcWSDm7XDeCBP3VHpwPC-ylcaGEM